---
label: Product
hide_body: false
fields:
- type: text
  name: id
  label: ID
- type: text
  name: title
  label: Title
- type: text
  name: description
  label: Description
- type: text
  name: price
  label: Price
- type: field_group
  name: images
  label: Images
  fields:
  - type: field_group
    name: default
    label: Default
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
  - type: field_group
    name: featured
    label: Featured
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
- type: select
  name: category
  label: Category
  config:
    source:
      type: simple
    options:
    - herbs
    - teas
    - gifts
    - formulas
    - tableware
    - cookware
- type: boolean
  name: featured
  label: Featured
- type: select
  name: section
  label: Section
  config:
    source:
      type: custom
    options:
    - Store
    - About
    - Home
- type: text
  name: layout
  label: Layout
  hidden: true
  default: product
  config:
    required: true
pages:
- products/103-oolong-ginseng-tea-103茶王-300g.md
- products/313-king-s-oolong-ginseng-tea-2nd-grade.md
- products/913-king-s-oolong-tea.md
- products/american-ginseng-美国花旗参-4-lbs.md
- products/angelica-sinensis-当归-1lb.md
- products/astragalus-黄芪-1-lb.md
- products/chrysanthemum-菊花-1-lb.md
- products/cordyceps-sinensis-冬蟲夏草-50g-1两.md
- products/custom-formula.md
- products/dried-scallops-干贝-1-lb.md
- products/eagle-brand-medicated-oil-風油精-1-dozen-24ml.md
- products/fish-bowl.md
- products/goji-berry-枸杞子-1lb.md
- products/herb-book.md
- products/herbal-pot.md
- products/korean-ginseng-tea.md
- products/lavender.md
- products/lian-hua-qing-wen-capsules.md
- products/lotus-seed-莲子-1-lb.md
- products/plant8.md
- products/plant9.md
- products/qing-fei-pai-du-tang.md
- products/reishi-灵芝.md
- products/sun-nest-bird-s-nest.md
- products/wild-american-ginseng-野生花旗参.md
- products/ziziphus-jujube-红枣-1-lb.md
